package net.teamio.director;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = CreeperDirector.MOD_ID, name = CreeperDirector.MOD_NAME, version = CreeperDirector.MOD_VERSION, guiFactory = CreeperDirector.GUI_FACTORY_CLASS)
public class CreeperDirectorMain {

	@Instance(CreeperDirector.MOD_ID)
	public static CreeperDirectorMain instance;

	@SidedProxy(clientSide = CreeperDirector.CLIENT_PROXY_CLASS, serverSide= CreeperDirector.SERVER_PROXY_CLASS)
	public static IProxy proxy;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata meta = event.getModMetadata();
		meta.authorList.add(CreeperDirector.MOD_AUTHOR1);
		// meta.authorList.add(CreepyDirector.MOD_AUTHOR2);
		meta.description = CreeperDirector.MOD_DESCRIPTION;
		meta.logoFile = CreeperDirector.MOD_LOGO_PATH;
		meta.autogenerated = false;

		FMLCommonHandler.instance().bus().register(new Config());
		
		Config.init(event.getSuggestedConfigurationFile());
		
		proxy.registerKeyBindings();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {

		FMLCommonHandler.instance().bus().register(new KeyHandler());
		
		proxy.registerClientTick();
	}
}
